spring:
  application:
    name: stew-api
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: password
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  mapper-locations: classpath:com/example/stew/**/mapper/*.xml
  type-handlers-package: com.example.stew.core.handler.mybatis
  configuration:
    map-underscore-to-camel-case: true

server:
  servlet:
    session:
      timeout: 30m
